### ISSUE TITLE
Return block height for vspds

### ISSUE THREAD

**Issue by xaur** [decred/dcrwebapi#142]
It would be good to have https://api.decred.org/?c=vsp return block heights just like it was added in #137.

Knowing height is very useful to see which VSPs are not syncing properly, and getting all this data from `?c=vsp` is much faster and easier than polling each VSP. I guess it could even be used by dcrwallet/Decrediton as a quick sanity check when suggesting a VSP to the user.

With https://github.com/decred/vspd/pull/254 merged, height info should be available when polling vspds (for those that have upgraded). As of writing I'm not seeing any mainnet vspds returning `blockheight` but this testnet one can be used for testing:

https://testnet-vsp.jholdstock.uk/api/v3/vspinfo

**Comment by jholdstock** [comment]
Can also consider adding proportion live

**Comment by jholdstock** [comment]
Required vspd PRs are decred/vspd#264 and decred/vspd#254. Both will be included in the next release of vspd, and then we can implement this issue.

**Comment by xaur** [comment]
I encountered a case where block height in `?c=vsp` response would be really handy.

For `dcrpool.ibitlin.com` this endpoint and the [VSP page](https://decred.org/vsp/) show 55 live tickets and a very fresh Last Updated timestamp. So for the end users it looks good and safe to use, but it's not the case. Thanks to https://github.com/decred/vspd/pull/254 , we can see that it [got stuck](https://dcrpool.ibitlin.com/api/v3/vspinfo) at block 666669 (Jun 10), its ticket stats are not changing since then, still it gives a fresh timestamp on each request. So end users cannot rely on Last Updated alone, I think they need to see the block height on the VSP page.

Ideally, VSP clients like dcrwallet and Decrediton would check block height and warn the user if it's too old.

**Comment by amass01** [comment]
would like to work on it 👀
