### ISSUE TITLE
dcr.ubiqsmart.com certificate expired

### ISSUE THREAD

**Issue by xaur** [decred/dcrwebapi#150]
@jyap808 could you please update the certificate at dcr.ubiqsmart.com?

https://www.ssllabs.com/ssltest/analyze.html?d=dcr.ubiqsmart.com

It manages 22 live tickets as of writing. I guess expired cert doesn't stop them from voting but it would be nice to remove API errors.

**Comment by jyap808** [comment]
Appreciate the heads up. This has been resolved. Issue can be closed.

Looks like Caddy v1 stopped renewing certs. Upgraded to Caddy v2.

**Comment by xaur** [comment]
Thanks for a quick fix! Cheers
