### ISSUE TITLE
dcrpool.ibitlin.com stuck on old block

### ISSUE THREAD

**Issue by xaur** [decred/dcrwebapi#166]
[dcrpool.ibitlin.com](https://dcrpool.ibitlin.com/api/v3/vspinfo) V3 API got stuck on block [666669](https://dcrdata.decred.org/block/666669) (2022-06-10). `voting`/`voted`/`revoked` ticket counts are not changing. Its certificate has expired on 2022-09-01 so it's a week of cert errors.

@lealife please fix it if you can, otherwise it is a candidate for delisting soon.

**Comment by jholdstock** [comment]
Messaged on Matrix September 5th.
Mentioned here on Github Sept 7th.
Emailed Sept 8th.

Let's give them a day or two more, then I agree they can be removed.

**Comment by lealife** [comment]
fixed

**Comment by xaur** [comment]
I confirm [the API](https://dcrpool.ibitlin.com/api/v3/vspinfo) works now with no certificate errors. Block height is recent and most of those 55 tickets moved from `voting` to `voted`.

Thanks for fixing and good to see you around!

**Comment by xaur** [comment]
@lealife out of curiosity, I thought most of those tickets would miss because vspd got stuck on an old block, but they show as voted now. Was it a display bug or something?

**Comment by lealife** [comment]
Sorry, i am woking on it

Jamie Holdstock ***@***.***> 于2022年9月8日周四 14:25写道：
