### ISSUE TITLE
Remove unused endpoints

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrwebapi#169]
With the deployment of decred/dcrweb#1056, I believe the endpoints `?c=dc` and `?c=gcs` are no longer used.

Review other projects to confirm, and then they can be removed from dcrwebapi.

**Comment by jholdstock** [comment]
Done in #170

**Comment by xaur** [comment]
For anyone wondering, the replacement for coin supply at dcrdata is https://dcrdata.decred.org/api/supply

See https://github.com/decred/dcrdata#apis for more endpoints and documentation.

**Comment by xaur** [comment]
dcrdata's [`/supply`](https://dcrdata.decred.org/api/supply) returns less data than [`gcs`](https://api.decred.org/?c=gcs), i.e. no PoW/PoS/etc percentages. I hope the change won't break https://dcrstats.com/ (I still find it useful for its "all important data on one page" dashboard). But if we have no contact with its admin I guess there's no safe way to find out if they are using `gcs` :S

**Comment by jholdstock** [comment]
Given [how the percentages were calculated](https://github.com/decred/dcrwebapi/blob/68063af910797db8ff92078a1cf35f1a0815ad18/service.go#L451-L453), they were always just estimated values anyway. Hard-coded 60/30/10 values were used for the subsidy split, so the estimates have been completely wrong since the subsidy split was changed.
