### ISSUE TITLE
decredvoting.com certificate expired

### ISSUE THREAD

**Issue by xaur** [decred/dcrwebapi#176]
Certificate for [decredvoting.com](https://decredvoting.com/) has expired. As a result it looks stalled on the [VSP page](https://decred.org/vsp/) and the [VSP list API](https://api.decred.org/?c=vsp).

Its own API reports good values though so the tickets should be good: https://decredvoting.com/api/v3/vspinfo

cc @David00

**Comment by David00** [comment]
Thank you, I'll take care of this shortly.

**Comment by David00** [comment]
This is done. Looks like my auto cert renewal script had a problem with my frontend config and failed while deploying the new cert. I've fixed that so my auto renewals should work properly next time. Thanks for tagging me!

**Comment by xaur** [comment]
Thanks for a quick fix!
