### ISSUE TITLE
Don't send testnet stakepools to dcrweb

### ISSUE THREAD

**Issue by xaur** [decred/dcrwebapi#42]
Is it reasonable to remove the testnet stakepool from this repository so it's not shown at https://decred.org/stakepools/ ?

Alternatively, add a query parameter or another path to get the testnet stakepools.

UI issue is decred/dcrweb#446

**Comment by dajohi** [comment]
no, it is used by other things other than dcrweb.

**Comment by xaur** [comment]
Right @njirap, decred/dcrweb#446 covers it.
