### ISSUE TITLE
Change PoolFees to VSPFees

### ISSUE THREAD

**Issue by ZeroASIC** [decred/dcrwebapi#43]
The API response contains a field called PoolFees that should be updated to VSPFees to match the new vernacular.  This is covered in issue decred/dcrweb#324 (Jargon update) and PR decred/dcrweb#435

**Comment by jrick** [comment]
I disagree with this idea.  This is API, and should remain stable unless there is a technical reason to change it.

**Comment by ZeroASIC** [comment]
That's completely fine with me.  PR decred/dcrweb#435 is ready to go then.  I'll just close this and move on.
