### ISSUE TITLE
List of PoW pools

### ISSUE THREAD

**Issue by ZeroASIC** [decred/dcrwebapi#52]
Add a list of PoW pools to the API so it can be pulled by dcrweb.  This pertains to https://github.com/decred/dcrweb/issues/433.

**Comment by dajohi** [comment]
What is the application for this?

**Comment by ZeroASIC** [comment]
We could just make a page and maintain it by hand.  Putting it in the API might be going overboard, and maintaining it in a fashion similar to exchanges might make more sense.  This was part of the discussion in decred/dcrweb#433.

**Comment by dajohi** [comment]
https://docs.decred.org/mining/overview/#sign-up-for-a-mining-pool
