### ISSUE TITLE
duplicate Access-Control-Allow-Origin header breaks website

### ISSUE THREAD

**Issue by jolan** [decred/dcrwebapi#8]
My web browser (Chromium 63) is throwing an error:

'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'https://decred.org' is therefore not allowed access.

I think this is because it is being set by both nginx and the API server.

https://github.com/decred/dcrwebapi/blob/b846ae75a5cb36c1d32c4888047b2bd93ff015c9/service.go#L546

**Comment by dajohi** [comment]
Fixed.
