### ISSUE TITLE
stakey.com down

### ISSUE THREAD

**Issue by dajohi** [decred/dcrwebapi#83]
prepare for removal unless @dema501 shows up

**Comment by dema501** [comment]
hold on, I'll fix it today

**Comment by dajohi** [comment]
you really should be on https://chat.decred.org

**Comment by dajohi** [comment]
@dema501 down for 20 days...

**Comment by jholdstock** [comment]
Seems to be back up now

**Comment by jrick** [comment]
can reopen if it's down/breaks again.
